name: main
run-name: ${{ github.actor }} triggered workflow
on: [workflow_dispatch]
jobs:
  test-using-other-action:
    runs-on: windows-latest
    steps:
      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.0.0
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          catalog: testing