name: main
run-name: ${{ github.actor }} triggered workflow
on: [workflow_dispatch, push]
jobs:
  run-sql-action:
    runs-on: windows-latest
    steps:
      - name: Install SQL Server
        uses: Curts0/install-sql-server-action@refs/heads/main
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          catalog: testing
  run-environment-var-check:
    name: Check Environment Variable
    runs-on: windows-latest
    needs: run-sql-action
    steps:
      - run: echo "$SQL_SERVER_CONNECTION_STRING"