name: main
run-name: ${{ github.actor }} triggered workflow
on: [workflow_dispatch, push]
jobs:
  run-sql-action:
    runs-on: windows-latest
    steps:
      - name: Install SQL Server
        uses: Curts0/install-sql-server-action@refs/heads/main
        with:
          connection-string-env-var: SQL_SERVER_CONNECTION_STRING
          catalog: testing
      - name: Check Environment Variable
        run: env
      - name: Run Python
        uses: actions/setup-python@v2
        run: python3 -m pip install python-tabular