name: Testing Simple Yamls
run-name: ${{ github.actor }} triggered workflow
on: [workflow_dispatch, push]
jobs:
  PythonRun:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PyTabular
        run: python3 -m pip install python-tabular
      - name: Run Python Script
        run: python3 readfile.py