name: Testing Simple Yamls
run-name: ${{ github.actor }} triggered workflow
on: [workflow_dispatch, push]
jobs:
  PythonRun:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 readfile.py